### ISSUE TITLE
Cap between featured image and sidebar

### ISSUE THREAD

**Issue by likewhoa** [NYC-Camp/website#140]
![untitled](https://f.cloud.github.com/assets/1696920/2400555/f2dabe24-aa0b-11e3-8d4c-849213619d7c.png)

I noticed this just now on mobile and will look into it. Anyone else seeing this?

**Comment by likewhoa** [comment]
Also 

``` css
.region-sidebar-first h3 {
margin: 0 0 24px;
}
```

is causing that big margin-bottom which looks funky on mobile.
